# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0069bcb9654e1a47d20698c502ff3eaef7afc32de6833b38aa4b2f31dc08cebde27da2226e96b4a3b4dd2556ee9fbdf9ab245a5c8a2246ad4dfce490bf5cf16b

test:
  secret_key_base: bed570fb0c29d8c2e9c20bb97300b50c6e9fe74c68d692b765f52c65b108c4a0860fce2ac1875dfaa34da3355f1d72a011f522ce2f5f37d914404bb605e28fea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
